"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-11

Hand-authored rather than autogenerated: this sandbox has no live Postgres
to diff against (alembic autogenerate needs a real DB connection to compare
target_metadata to). Every column/type here is a direct mirror of
app/models.py at the time this was written - if you change models.py without
regenerating from a real DB, re-check this file matches before running it.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "agents",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("email", sa.String, nullable=False),
        sa.Column("phone", sa.String),
        sa.Column("brokerage", sa.String),
        sa.Column("license_no", sa.String),
        sa.Column("role", sa.String, server_default="agent"),
        sa.Column("hashed_password", sa.String, nullable=False),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )
    op.create_unique_constraint("uq_agents_email", "agents", ["email"])
    op.create_index("ix_agents_email", "agents", ["email"])

    contact_type = postgresql.ENUM("buyer", "seller", "both", name="contacttype")
    contact_status = postgresql.ENUM(
        "new_lead", "active", "showing", "under_contract", "past_client", name="contactstatus"
    )
    op.create_table(
        "contacts",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("agent_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("first_name", sa.String, nullable=False),
        sa.Column("last_name", sa.String, nullable=False),
        sa.Column("email", sa.String),
        sa.Column("phone", sa.String),
        sa.Column("contact_type", contact_type, nullable=False),
        sa.Column("lead_source", sa.String),
        sa.Column("status", contact_status, server_default="new_lead"),
        sa.Column("portal_password_hash", sa.String),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("last_contacted_at", sa.DateTime),
    )
    op.create_index("ix_contacts_agent_id", "contacts", ["agent_id"])
    op.create_index("ix_contacts_email", "contacts", ["email"])

    op.create_table(
        "buyer_profiles",
        sa.Column("contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), primary_key=True),
        sa.Column("budget_min", sa.Numeric),
        sa.Column("budget_max", sa.Numeric),
        sa.Column("preferred_locations", postgresql.ARRAY(sa.String)),
        sa.Column("preferred_beds", sa.Integer),
        sa.Column("preferred_baths", sa.Integer),
        sa.Column("preapproval_status", sa.String),
        sa.Column("preapproval_amount", sa.Numeric),
        sa.Column("lender_name", sa.String),
    )

    op.create_table(
        "seller_profiles",
        sa.Column("contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), primary_key=True),
        sa.Column("property_address", sa.String),
        sa.Column("listing_timeline", sa.String),
        sa.Column("expected_price", sa.Numeric),
        sa.Column("mortgage_payoff", sa.Numeric),
        sa.Column("reason_for_selling", sa.Text),
    )

    property_status = postgresql.ENUM("active", "pending", "closed", "withdrawn", name="propertystatus")
    op.create_table(
        "properties",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("agent_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("seller_contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), nullable=True),
        sa.Column("address", sa.String, nullable=False),
        sa.Column("mls_number", sa.String),
        sa.Column("list_price", sa.Numeric),
        sa.Column("status", property_status, server_default="active"),
        sa.Column("days_on_market", sa.Integer, server_default="0"),
        sa.Column("beds", sa.Integer),
        sa.Column("baths", sa.Integer),
        sa.Column("sqft", sa.Integer),
        sa.Column("photos", postgresql.ARRAY(sa.String)),
    )

    deal_type = postgresql.ENUM("buy", "sell", name="dealtype")
    deal_stage = postgresql.ENUM(
        "lead", "nurture", "showing", "offer", "under_contract", "closed", "lost", name="dealstage"
    )
    op.create_table(
        "deals",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), nullable=False),
        sa.Column("agent_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("properties.id"), nullable=True),
        sa.Column("deal_type", deal_type, nullable=False),
        sa.Column("stage", deal_stage, server_default="lead"),
        sa.Column("list_price", sa.Numeric),
        sa.Column("offer_price", sa.Numeric),
        sa.Column("close_date", sa.DateTime),
        sa.Column("commission_pct", sa.Numeric),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )
    op.create_index("ix_deals_contact_id", "deals", ["contact_id"])

    op.create_table(
        "saved_listings",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("buyer_contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("properties.id"), nullable=False),
        sa.Column("agent_curated", sa.Boolean, server_default=sa.true()),
        sa.Column("buyer_feedback", sa.Text),
        sa.Column("feedback_rating", sa.Integer),
        sa.Column("status", sa.String, server_default="new"),
    )
    op.create_index("ix_saved_listings_buyer_contact_id", "saved_listings", ["buyer_contact_id"])

    op.create_table(
        "showings",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("property_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("properties.id"), nullable=False),
        sa.Column("buyer_contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), nullable=True),
        sa.Column("agent_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("scheduled_at", sa.DateTime, nullable=False),
        sa.Column("type", sa.String, server_default="private"),
        sa.Column("feedback_text", sa.Text),
        sa.Column("feedback_rating", sa.Integer),
    )

    op.create_table(
        "offers",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("deal_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("deals.id"), nullable=False),
        sa.Column("offer_amount", sa.Numeric, nullable=False),
        sa.Column("buyer_contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id")),
        sa.Column("status", sa.String, server_default="submitted"),
        sa.Column("submitted_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("contingencies", sa.Text),
    )
    op.create_index("ix_offers_deal_id", "offers", ["deal_id"])

    doc_status = postgresql.ENUM("draft", "sent", "signed", name="docstatus")
    op.create_table(
        "documents",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("deal_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("deals.id"), nullable=True),
        sa.Column("contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), nullable=False),
        sa.Column("uploaded_by", postgresql.UUID(as_uuid=False), sa.ForeignKey("agents.id")),
        sa.Column("doc_type", sa.String, nullable=False),
        # file_url stores the S3 object key, not a public URL - see services/storage.py
        sa.Column("file_url", sa.String, nullable=False),
        sa.Column("status", doc_status, server_default="draft"),
        sa.Column("esign_provider_ref", sa.String),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )
    op.create_index("ix_documents_deal_id", "documents", ["deal_id"])
    op.create_index("ix_documents_contact_id", "documents", ["contact_id"])

    activity_type = postgresql.ENUM(
        "note", "call", "showing", "doc_sent", "email", "sms", "reminder", name="activitytype"
    )
    op.create_table(
        "activities",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), nullable=False),
        sa.Column("deal_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("deals.id"), nullable=True),
        sa.Column("agent_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("type", activity_type, nullable=False),
        sa.Column("content", sa.Text),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("is_automated", sa.Boolean, server_default=sa.false()),
    )
    op.create_index("ix_activities_contact_id", "activities", ["contact_id"])
    op.create_index("ix_activities_created_at", "activities", ["created_at"])

    op.create_table(
        "workflows",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("agent_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("trigger_event", sa.String, nullable=False),
        sa.Column("steps", sa.JSON, nullable=False),
        sa.Column("is_active", sa.Boolean, server_default=sa.true()),
    )

    op.create_table(
        "workflow_enrollments",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), nullable=False),
        sa.Column("workflow_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("workflows.id"), nullable=False),
        sa.Column("current_step", sa.Integer, server_default="0"),
        sa.Column("status", sa.String, server_default="active"),
        sa.Column("enrolled_at", sa.DateTime, server_default=sa.func.now()),
    )
    op.create_index("ix_workflow_enrollments_contact_id", "workflow_enrollments", ["contact_id"])

    op.create_table(
        "cma_reports",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("deal_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("deals.id"), nullable=True),
        sa.Column("subject_property", sa.JSON, nullable=False),
        sa.Column("comparables", sa.JSON, nullable=False),
        sa.Column("suggested_price", sa.Numeric),
        sa.Column("generated_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("shared_with_contact_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("contacts.id"), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("cma_reports")
    op.drop_table("workflow_enrollments")
    op.drop_table("workflows")
    op.drop_table("activities")
    op.drop_table("documents")
    op.drop_table("offers")
    op.drop_table("showings")
    op.drop_table("saved_listings")
    op.drop_table("deals")
    op.drop_table("properties")
    op.drop_table("seller_profiles")
    op.drop_table("buyer_profiles")
    op.drop_table("contacts")
    op.drop_table("agents")

    # Drop enum types last - Postgres won't drop a type still referenced by a column
    for enum_name in [
        "contacttype", "contactstatus", "propertystatus", "dealtype", "dealstage",
        "docstatus", "activitytype",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
